apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - redis-pvc.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - username-distribution-deployment.yaml
  - username-distribution-route.yaml
  - username-distribution-service.yaml